package interfaz;

import logica.AnalizadorProposicional;
import logica.Nodo;
import logica.Parser;
import java.awt.Color;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;

/**
 * La interfaz principal de la aplicación donde esta para ingresar la formula,
 * observar la tabla de verdad y el tableaux
 *
 * @author Carlos Toro, Gustavo Salgado y Laura Rúa
 * @version 1.0
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Cadena que guarda la formula ingresada
     */
    public String formula = "";
    /**
     * Arreglo de posiciones que permite generar las estadistica de la formula 
     */
    Object[] estad = new Object[4];
    /**
     * Arraylist de la formula
     */
    ArrayList<String> formulas = new ArrayList<>();

    /**
     * Variable tipo nodo del arbol
     */
    private Nodo arbolS;
    /**
     * Instancia del analizador proposicional
     */
    private AnalizadorProposicional analizador;

    /**
     * Metodo constructor de la ventana
     */
    public Ventana() {
        initComponents();
        setLocationRelativeTo(null);

        validarTeclado();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cVisorFormula = new javax.swing.JTextArea();
        btY = new javax.swing.JButton();
        btO = new javax.swing.JButton();
        btCondicional = new javax.swing.JButton();
        btNegacion = new javax.swing.JButton();
        btBiCondicional = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btParentesis = new javax.swing.JButton();
        btnY = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnQ = new javax.swing.JButton();
        btnZ = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnV = new javax.swing.JButton();
        btnW = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btAnalizar = new javax.swing.JButton();
        jLEstad = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVerdad = new javax.swing.JTable();
        btAnalizar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btConjuntoF = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuEj1 = new javax.swing.JMenuItem();
        menuEj2 = new javax.swing.JMenuItem();
        menuEj6 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jButton7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton7.setText("()^()");

        jButton8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton8.setText("()V()");

        jButton9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton9.setText("()V()");

        jButton10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton10.setText("()^()");

        jButton11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton11.setText("()V()");

        jButton17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton17.setText("()V()");

        jButton18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton18.setText("()^()");

        jButton19.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton19.setText("()^()");

        jButton20.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton20.setText("()V()");

        jButton21.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton21.setText("()V()");

        jButton22.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton22.setText("()V()");

        jButton23.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton23.setText("()^()");

        jButton24.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton24.setText("()V()");

        jButton25.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton25.setText("()^()");

        jButton26.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton26.setText("()V()");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Fórmula");

        cVisorFormula.setColumns(20);
        cVisorFormula.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        cVisorFormula.setLineWrap(true);
        cVisorFormula.setRows(5);
        cVisorFormula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cVisorFormulaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(cVisorFormula);

        btY.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btY.setText("()V()");
        btY.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btY.setPreferredSize(new java.awt.Dimension(51, 30));
        btY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btYActionPerformed(evt);
            }
        });

        btO.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btO.setText("()^()");
        btO.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btO.setPreferredSize(new java.awt.Dimension(51, 30));
        btO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOActionPerformed(evt);
            }
        });

        btCondicional.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btCondicional.setText("()→()");
        btCondicional.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btCondicional.setPreferredSize(new java.awt.Dimension(51, 30));
        btCondicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCondicionalActionPerformed(evt);
            }
        });

        btNegacion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btNegacion.setText("¬()");
        btNegacion.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btNegacion.setPreferredSize(new java.awt.Dimension(51, 30));
        btNegacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNegacionActionPerformed(evt);
            }
        });

        btBiCondicional.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btBiCondicional.setText("()↔()");
        btBiCondicional.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBiCondicional.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btBiCondicional.setPreferredSize(new java.awt.Dimension(51, 30));
        btBiCondicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBiCondicionalActionPerformed(evt);
            }
        });

        btnR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnR.setText("r");
        btnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRActionPerformed(evt);
            }
        });

        btParentesis.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btParentesis.setText("()");
        btParentesis.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btParentesis.setPreferredSize(new java.awt.Dimension(51, 30));
        btParentesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btParentesisActionPerformed(evt);
            }
        });

        btnY.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnY.setText("y");
        btnY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYActionPerformed(evt);
            }
        });

        btnT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnT.setText("t");
        btnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTActionPerformed(evt);
            }
        });

        btnP.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnP.setText("p");
        btnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPActionPerformed(evt);
            }
        });

        btnQ.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnQ.setText("q");
        btnQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQActionPerformed(evt);
            }
        });

        btnZ.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnZ.setText("z");
        btnZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZActionPerformed(evt);
            }
        });

        btnU.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnU.setText("u");
        btnU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUActionPerformed(evt);
            }
        });

        btnV.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnV.setText("v");
        btnV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVActionPerformed(evt);
            }
        });

        btnW.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnW.setText("w");
        btnW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWActionPerformed(evt);
            }
        });

        btnS.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnS.setText("s");
        btnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSActionPerformed(evt);
            }
        });

        btnX.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnX.setText("x");
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        btAnalizar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btAnalizar.setText("Analizar");
        btAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnalizarActionPerformed(evt);
            }
        });

        jLEstad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLEstad.setText("Estadística: ");

        jTabbedPane1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tableaux", jPanel2);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tablaVerdad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaVerdad);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tabla de Verdad", jPanel1);

        btAnalizar1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btAnalizar1.setText("Limpiar");
        btAnalizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnalizar1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Operadores");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Formas Atómicas");

        btConjuntoF.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btConjuntoF.setText(",");
        btConjuntoF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btConjuntoF.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btConjuntoF.setPreferredSize(new java.awt.Dimension(51, 30));
        btConjuntoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConjuntoFActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/analizar48.png"))); // NOI18N
        jMenuItem3.setText("Analizar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/salir48.png"))); // NOI18N
        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenu2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/ejemplos48.png"))); // NOI18N
        jMenu3.setText("Ejemplos");
        jMenu3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        menuEj1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        menuEj1.setText("2 Condiciones");
        menuEj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEj1ActionPerformed(evt);
            }
        });
        jMenu3.add(menuEj1);

        menuEj2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        menuEj2.setText("4 Condiciones");
        menuEj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEj2ActionPerformed(evt);
            }
        });
        jMenu3.add(menuEj2);

        menuEj6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        menuEj6.setText("6 Condiciones");
        menuEj6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEj6ActionPerformed(evt);
            }
        });
        jMenu3.add(menuEj6);

        jMenu2.add(jMenu3);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/ayuda48.png"))); // NOI18N
        jMenuItem1.setText("Manual");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/acerca48.png"))); // NOI18N
        jMenuItem2.setText("Acerca de");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btParentesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11)
                                    .addComponent(btNegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btBiCondicional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btConjuntoF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btCondicional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jLabel2))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnP)
                                    .addComponent(btnV))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnQ)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnR, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(btnS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(btnT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnU))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnW)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnX)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnY)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnZ, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAnalizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLEstad, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btParentesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btNegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(btO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btCondicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btBiCondicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnP)
                                        .addComponent(btnQ)
                                        .addComponent(btnR)
                                        .addComponent(btnS))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnT)
                                        .addComponent(btnU)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnV)
                                    .addComponent(btnW)
                                    .addComponent(btnX)
                                    .addComponent(btnY)
                                    .addComponent(btnZ))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btAnalizar1)
                                    .addComponent(btAnalizar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConjuntoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(jLEstad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btYActionPerformed
        escribir(btY.getText());
//        formula = Parser.ingresar(formula, btY.getText());
//        cVisorFormula.setText(formula);
    }//GEN-LAST:event_btYActionPerformed

    private void btBiCondicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBiCondicionalActionPerformed
        escribir(btBiCondicional.getText());
    }//GEN-LAST:event_btBiCondicionalActionPerformed

    private void btOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOActionPerformed
        escribir(btO.getText());
    }//GEN-LAST:event_btOActionPerformed

    private void btNegacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNegacionActionPerformed
        escribir(btNegacion.getText());
    }//GEN-LAST:event_btNegacionActionPerformed

    private void cVisorFormulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cVisorFormulaKeyReleased
        //noRecibirLetras(evt);
        //escribir(evt);
    }//GEN-LAST:event_cVisorFormulaKeyReleased

    private void btParentesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btParentesisActionPerformed
        escribir(btParentesis.getText());
    }//GEN-LAST:event_btParentesisActionPerformed

    private void btCondicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCondicionalActionPerformed
        escribir(btCondicional.getText());
    }//GEN-LAST:event_btCondicionalActionPerformed

    private void btAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnalizarActionPerformed
        analizarFormulas();
    }//GEN-LAST:event_btAnalizarActionPerformed

    private void menuEj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEj1ActionPerformed
        cVisorFormula.setText("(p)↔(r)");
    }//GEN-LAST:event_menuEj1ActionPerformed

    private void menuEj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEj2ActionPerformed
        cVisorFormula.setText("((p)↔(r))V((s)^(t))");
    }//GEN-LAST:event_menuEj2ActionPerformed

    private void menuEj6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEj6ActionPerformed
        cVisorFormula.setText("((p)→(q))V((¬(p))↔((t)^((x)↔(z))))");
    }//GEN-LAST:event_menuEj6ActionPerformed

    private void btnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPActionPerformed
        escribir(btnP.getText());
//        formula = Parser.ingresar(formula, btnP.getText());
//        cVisorFormula.setText(formula);
    }//GEN-LAST:event_btnPActionPerformed

    private void btnQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQActionPerformed
        escribir(btnQ.getText());
    }//GEN-LAST:event_btnQActionPerformed

    private void btnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRActionPerformed
        escribir(btnR.getText());
    }//GEN-LAST:event_btnRActionPerformed

    private void btnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSActionPerformed
        escribir(btnS.getText());
    }//GEN-LAST:event_btnSActionPerformed

    private void btnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTActionPerformed
        escribir(btnT.getText());
    }//GEN-LAST:event_btnTActionPerformed

    private void btnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUActionPerformed
        escribir(btnU.getText());
    }//GEN-LAST:event_btnUActionPerformed

    private void btnVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVActionPerformed
        escribir(btnV.getText());
    }//GEN-LAST:event_btnVActionPerformed

    private void btnWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWActionPerformed
        escribir(btnW.getText());
    }//GEN-LAST:event_btnWActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        escribir(btnX.getText());
    }//GEN-LAST:event_btnXActionPerformed

    private void btnYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYActionPerformed
        escribir(btnY.getText());
    }//GEN-LAST:event_btnYActionPerformed

    private void btnZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZActionPerformed
        escribir(btnZ.getText());
    }//GEN-LAST:event_btnZActionPerformed

    private void btAnalizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnalizar1ActionPerformed
        cVisorFormula.setText("");
        jLEstad.setText("");
        tablaVerdad.setModel(new DefaultTableModel());
    }//GEN-LAST:event_btAnalizar1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Ayuda().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btConjuntoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConjuntoFActionPerformed
        escribir(btConjuntoF.getText());
    }//GEN-LAST:event_btConjuntoFActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        analizarFormulas();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        devsInfo();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnalizar;
    private javax.swing.JButton btAnalizar1;
    private javax.swing.JButton btBiCondicional;
    private javax.swing.JButton btCondicional;
    private javax.swing.JButton btConjuntoF;
    private javax.swing.JButton btNegacion;
    private javax.swing.JButton btO;
    private javax.swing.JButton btParentesis;
    private javax.swing.JButton btY;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnQ;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnT;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnV;
    private javax.swing.JButton btnW;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnY;
    private javax.swing.JButton btnZ;
    private javax.swing.JTextArea cVisorFormula;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLEstad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem menuEj1;
    private javax.swing.JMenuItem menuEj2;
    private javax.swing.JMenuItem menuEj6;
    private javax.swing.JTable tablaVerdad;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo que permite escribir e identificar la ubicacion de la letra presionada
     * @param valor cadena que se va a escribir
     */
    private void escribir(String valor) {
        try {
            cVisorFormula.getDocument().insertString(cVisorFormula.getCaretPosition(), valor, null);
        } catch (BadLocationException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, "No se logro escribir en Display", ex);
        }
    }

    /**
     * Metodo que permite escribir e identificar la letra presionada
     * @param evt evento del teclado
     */
    private void escribir(java.awt.event.KeyEvent evt) {
        //97 = a q= 113 z=122
        String form = cVisorFormula.getText();
        System.out.println("Tecla Presionada ..." + evt.getKeyCode());
//        if (evt.getKeyCode() >= 65 && evt.getKeyCode() <= 90) {
//            escribir(String.valueOf(evt.getKeyChar()));
//        }else{
//            evt.consume();
//        }

        if (evt.getKeyCode() < 65 && evt.getKeyChar() > 90) {
            evt.consume();
        }
    }

    /**
     * Metodo que valida el texto ingresado, y  limita lo que se desea ingresar
     * @see
     * http://www.javacreed.com/how-to-capture-key-events-with-jframe-or-window/
     */
    private void validarTeclado() {
        cVisorFormula.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                int c = e.getKeyChar();
                //System.out.println("Tecla presionada " + c);
                if (c < 112 || c > 122) {
                    e.consume();
                }
            }
        });
    }

    /**
     * Metodo que analiza la formula que se le ingresa a traves del textArea
     */
    private void analizarFormulas() {
        formulas.clear();
        Parser.hallarFormulas(cVisorFormula.getText().replace(" ", ""));
        formulas = Parser.getFormulas();
        if (Parser.bienFormada(formulas)) {

            Parser.encontrarFormulasRepetidas();
            Parser.literales(formulas);
            Parser.construirTabla();

            if (Parser.getAtomos().size() >= 5) {
                boolean sa = Parser.verSatisfacibilidad(Parser.getTabla());
                if (sa) {
                    estad[3] = "Es satisfacible";
                    dibujarArbol();
                } else {
                    estad[3] = "No es satisfacible";
                }

                imprimirTablaConsola();
                estadistica();
            } else {
                JOptionPane.showMessageDialog(this, "Debe Ingresar Mínimo 5\nFormas Proposicionales Atómicas");
                jLEstad.setText("");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Ingresó una fórmula mal formada");
        }
    }

    /**
     * Metodo que imprima la tabla de verdad de la formula en la consola
     */
    private void imprimirTablaConsola() {
        String aux = "";
        for (int i = 0; i < Parser.getTabla().length; i++) {
            for (int j = 0; j < Parser.getTabla()[0].length; j++) {
                aux += Parser.getTabla()[i][j] + " ";
            }
            aux += "\n";
        }

        System.out.print(aux);

        for (int i = 0; i < Parser.getFormulas().size(); i++) {
            System.out.println(" " + Parser.getFormulas().get(i));
        }

        String[] cols = new String[Parser.getSubFormulas().size()];
        cols = Parser.getSubFormulas().toArray(cols);

        Object[][] auxT = Parser.getTabla();
        Object[][] tablaAux = new Object[auxT.length - 1][auxT[0].length];

        for (int x = 1; x < Parser.getTabla().length; x++) {
            for (int y = 0; y < Parser.getTabla()[x].length; y++) {
                tablaAux[x - 1][y] = auxT[x][y];
            }
        }

        int con = 0;
        for (int x = 0; x < auxT.length; x++) {
            if (auxT[x][auxT[0].length - 1].equals(1)) {
                con++;
            }
        }
        System.out.println("Con: " + con);
        System.out.println("Tam: " + auxT.length);
        if (con == auxT.length - 1) {
            estad[2] = "Es tautología";
        } else {
            estad[2] = "No es tautología";
        }

        DefaultTableModel model = new DefaultTableModel(tablaAux, cols);
        tablaVerdad.setModel(model);
    }

    /**
     * Metodo que recopila la informacion de la formula guardada en un arreglo y la muestra en la interfaz
     */
    public void estadistica() {
        char op = Parser.buscarOpPrincipal(Parser.getFormulas().get(0));
        estad[0] = "Operador principal: " + op;
        int num = Parser.getAtomos().size();
        estad[1] = "N° átomos: " + num;
        System.out.println("Caracter: " + op);
        jLEstad.setText("Estadistica: " + estad[0] + " | " + estad[1] + " | " + estad[2] + " | " + estad[3]);

    }

    /**
     * Metodo que permite dibujar el arbol
     */
    private void dibujarArbol() {
        try {
            paint(getGraphics());
            boolean sintactico = false;

            analizador = new AnalizadorProposicional();
            arbolS = analizador.crearArbolSintactico(cVisorFormula.getText());

            System.out.println("pArbolSintactico.getHeight() " + jPanel2.getHeight());
            if (sintactico == false) {
                arbolS.dibujarSubformula(arbolS,
                        jPanel2.getWidth() / 2, jPanel2.getHeight() - 420,
                        jPanel2.getWidth() / 2, jPanel2.getHeight() - 420,
                        jPanel2, Color.GREEN);

                System.out.println("arbol " + arbolS);

            } else if (sintactico == true) {
                arbolS.dibujarArbolSintactico(jPanel2.getGraphics(), arbolS,
                        jPanel2.getWidth() / 2, jPanel2.getHeight() - 420,
                        jPanel2.getWidth() / 2, jPanel2.getHeight() - 420,
                        jPanel2, Color.GREEN);

            }
        } catch (Exception ex) {
            Logger.getLogger(Ventana.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * Informacion sobre los creadores del Software
     */
    private void devsInfo() {
        JOptionPane.showMessageDialog(null, "Materia: Lógica Formal - Alejandra Pulgarin\n"
                + "Universidad del Quindio 2017\n"
                + "Devs:\n"
                + "Laura Rúa\n"
                + "Carlos Toro\n"
                + "Gustavo Salgado");
    }

}
